"""
Strategy base classes and core data structures for AlphaSMART.

Signal   — intent from strategy (direction decision)
Order    — instruction to trade (what to execute)
Fill     — confirmed execution record
Strategy — abstract base class all strategies implement
"""
from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime
from typing import TYPE_CHECKING, Literal, Optional

import pandas as pd

if TYPE_CHECKING:
    from src.strategy.portfolio import Portfolio


# ---------------------------------------------------------------------------
# Core data structures
# ---------------------------------------------------------------------------

@dataclass
class Signal:
    """
    Trading intent generated by a strategy at a given bar.
    direction='long'  → strategy wants to be long
    direction='flat'  → strategy wants no position (exit or stay out)
    """
    symbol: str
    direction: Literal["long", "flat"]
    strength: float = 1.0          # 0–1, scales position size
    timestamp: Optional[datetime] = None
    reason: str = ""               # Human-readable explanation
    metadata: dict = field(default_factory=dict)

    def __post_init__(self) -> None:
        if not 0.0 <= self.strength <= 1.0:
            raise ValueError(f"Signal strength must be 0–1, got {self.strength}")
        if self.direction not in ("long", "flat"):
            raise ValueError(f"Invalid direction: {self.direction}")


@dataclass
class Order:
    """
    Instruction to trade. Created by strategy.size_position(), validated by RiskEngine.
    """
    symbol: str
    side: Literal["buy", "sell"]
    quantity: float                # Number of shares / contracts
    order_type: Literal["market"] = "market"  # Phase 2: market orders only
    timestamp: Optional[datetime] = None
    strategy_name: str = ""

    def __post_init__(self) -> None:
        if self.quantity <= 0:
            raise ValueError(f"Order quantity must be positive, got {self.quantity}")
        if self.side not in ("buy", "sell"):
            raise ValueError(f"Invalid side: {self.side}")


@dataclass
class Fill:
    """
    Confirmed execution. Includes actual fill price (after slippage) and commission.
    """
    order: Order
    fill_price: float              # Actual execution price (includes slippage)
    commission: float              # Absolute commission amount
    slippage_cost: float           # Absolute slippage cost (informational)
    timestamp: datetime

    @property
    def gross_value(self) -> float:
        """Trade value before commission."""
        return self.fill_price * self.order.quantity

    @property
    def net_cash_impact(self) -> float:
        """
        Net cash change from this fill (positive = cash received, negative = cash spent).
        Buy:  -(fill_price * qty + commission)
        Sell: +(fill_price * qty - commission)
        """
        if self.order.side == "buy":
            return -(self.fill_price * self.order.quantity + self.commission)
        return self.fill_price * self.order.quantity - self.commission


# ---------------------------------------------------------------------------
# Abstract base strategy
# ---------------------------------------------------------------------------

class Strategy(ABC):
    """
    Abstract base class for all AlphaSMART strategies.

    Subclasses must implement:
        generate_signals(data) → Signal
        size_position(signal, portfolio) → Optional[Order]

    Contract:
        generate_signals() MUST only use data up to the latest bar (no lookahead).
        size_position() MUST NOT modify portfolio state.
    """

    name: str = "base"

    @abstractmethod
    def generate_signals(self, data: pd.DataFrame) -> Signal:
        """
        Given OHLCV + indicator data up to the current bar, return a Signal.

        Args:
            data: pd.DataFrame with columns [open, high, low, close, volume, indicators...]
                  Last row = current bar. Strategy MUST NOT use data beyond last row.

        Returns:
            Signal with direction and strength for the primary symbol.
        """

    @abstractmethod
    def size_position(self, signal: Signal, portfolio: "Portfolio", price: float) -> Optional[Order]:
        """
        Convert a Signal into an Order, given current portfolio state and price.
        Returns None if no order should be placed.

        Args:
            signal:    Signal from generate_signals()
            portfolio: Current portfolio state (read-only use)
            price:     Current close price (use for share quantity calculation)
                       Engine executes at next bar open — this is a sizing hint only.

        Returns:
            Order with quantity in shares, or None.
        """

    def __repr__(self) -> str:
        return f"{self.__class__.__name__}(name={self.name!r})"
